# Generated by Django 2.0.2 on 2018-09-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=5000)),
                ('pub_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
